development:
  adapter: mysql2
  encoding: utf8
  database: dev_twenty45
  username: root
  password: Palo5non!
test:
  adapter: mysql2
  database: test_twenty45
  username: root
  password: Palo5non!
production:
  adapter: mysql2
  encoding: utf8
  database: sch_twenty45 mydb
  username: root
  password: Palo5non!